= Server
Ayman Patel
:toc: 


== Tech stack

1. Postgresql
2. GraphQL
3. TypeORM


== Environment Variables

Libraries used for `env` management

1. https://www.npmjs.com/package/dotenv-safe[dotenv-safe]
   - Identical to `dotenv``, but ensures that all necessary environment variables are defined after reading from `.env`
2. https://www.npmjs.com/package/gen-env[gen-env]
  - auto generate .env template by scanning source code
  - `gen-env-types .env -o src/env.d.ts -e .`: Creates type defn. in `src/env.d.ts`
  - Can be used as `process.env.<your-key>`

== MikroORM
 
`npx mikro-orm migration:create`

Creates Migrations under `/migrations` based on `entities`


== GraphQL 

== Code gen

`npm run graphql-codegen` will spit out `graphql.schema.json` and type definitions `graphql.ts` under `src/generated`

The npm command uses `codegen.yml`

Libraries used: 

```
"graphql-codegen": "graphql-codegen --config codegen.yml"
"@graphql-codegen/cli": "2.3.1",

// Plugins
    "@graphql-codegen/typescript": "2.4.2",
    "@graphql-codegen/typescript-resolvers": "2.4.3",
    "@graphql-codegen/introspection": "2.1.1"

```

=== Queries

==== Posts

```
mutation { 
  createPost(title: "UPDATE from GraphQL") {
    id
    createdAt
    updatedAt
    title
  }
}
mutation {
  updatePost(id: 23,title: "UPDATE from GraphQL") {
    id
    createdAt
    updatedAt
    title
  }
}
mutation {
  deletePost(id: 4)
}
```

==== User

```
mutation{
  register(options: {username: "fefegr", password: "2fdkjrlsrdt"} ) {
     user {
      username
      updatedAt
      createdAt
  } 
    errors {
      field
      message
    }
  }
}
mutation{
  login(options: {username: "fefer", password: "2fdkjrlsrt"} ) {
    
  errors{
      field
      message
    }
   user {
    username
    updatedAt
    createdAt
  } 
    
  }
}
```

== Sessions

NOTE: To make `me` query work in GraphQL playground, set GraphQL Settings `  "request.credentials": "include",` 

Sessions are being sent to Redis 

Example in Redis:

Key: 

`sess:_9iqivBaXhLEUSM8PD3YFxsroVr_LLGI`

Value: 

```
{"cookie":{"originalMaxAge":328500000000,"expires":"2032-05-28T09:40:49.357Z","secure":false,"httpOnly":true,"path":"/","sameSite":"lax"},"userId":13}
```


=== Sequence 

1. `req.session.userId = user.id`

2. {userId: 13} -> Sent to redis with key `sess:_9iqivBaXhLEUSM8PD3YFxsroVr_LLGI`

3.Login: Express sets cookie with key: `qid`(set in config `session({name: "qid"//` and value: `_9iqivBaXhLEUSM8PD3YFxsroVr_LLGI`

4. After login: When User makes request 
signed(_9iqivBaXhLEUSM8PD3YFxsroVr_LLGI) [Signing key is `secret` configured] -> Server

5. Make request to redis 